name: CI

on:
  - push

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        account:
          - principal
          - production
          - testing
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.18
        tf_actions_subcommand: init
        tf_actions_working_dir: ${{ matrix.account }}
    - name: Format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.18
        tf_actions_subcommand: fmt
        tf_actions_working_dir: ${{ matrix.account }}
    - name: Validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.18
        tf_actions_subcommand: validate
        tf_actions_working_dir: ${{ matrix.account }}
